# Generated by Django 5.2.1 on 2025-05-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_icon', models.ImageField(upload_to='img')),
                ('app_name', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=1)),
            ],
        ),
    ]
